default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:
  password:

development:
  <<: *default
  database: price_survey_app_development

test:
  <<: *default
  database: price_survey_app_test

production:
  <<: *default
  database: price_survey_app_production
